name: CI Pipeline

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 10 # Wait for services to be ready

      - name: Run Migrations
        run: docker compose exec web python manage.py migrate

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Jest Tests for Frontend
        run: |
          cd frontend # Navigate to the frontend directory
          npm test -- --coverage # Run Jest tests for React Native

      - name: Run Backend Tests
        run: docker compose exec web pytest

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Launch Simulator
        id: sim
        uses: futureware-tech/simulator-action@v4

      - name: Install the Application
        run: |
          flutter run -d ${{steps.sim.outputs.udid}} &
          while ! xcrun simctl get_app_container booted host.exp.Exponent; do 
            sleep 5
          done;

      - name: Install Maestro
        run: curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: Maestro test
        run: maestro record maestro/acceptance/*.yaml --local test.mp4

      - name: Upload Test Video
        uses: actions/upload-artifact@v4
        with:
          name: test-video
          path: test.mp4
