name: CI Pipeline

on:
  push:
    branches:
      - main
      - Marc # Run on push to the 'Marc' branch
  pull_request:
    branches:
      - main # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 10 # Wait for services to be ready

      - name: Run Migrations
        run: docker compose exec web python manage.py migrate

      - name: Run Tests
        run: docker compose exec web pytest
