name: CI Pipeline

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 10 # Wait for services to be ready

      - name: Run Migrations
        run: docker compose exec web python manage.py migrate

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Jest Tests for Frontend
        run: |
          cd frontend # Navigate to the frontend directory
          npm test -- --coverage # Run Jest tests for React Native

      - name: Run Backend Tests
        run: docker compose exec web pytest

  maestro-tests:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Start Expo app
        run: |
          cd frontend
          npm run ios & # Start Expo in the background

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: Wait for the iOS emulator to be ready
        run: |
          while ! xcrun simctl list devices | grep "(Booted)"; do
            echo "Waiting for emulator to start..."
            sleep 5
          done

      - name: Run Maestro tests
        run: |
          cd frontend
          export PATH="$PATH":"$HOME/.maestro/bin"
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=60000
          maestro test maestro/acceptance/*.yaml
