name: CI Pipeline

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 10 # Wait for services to be ready

      - name: Run Migrations
        run: docker compose exec web python manage.py migrate

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Jest Tests for Frontend
        run: |
          cd frontend # Navigate to the frontend directory
          npm test -- --coverage # Run Jest tests for React Native

      - name: Run Backend Tests
        run: docker compose exec web pytest

  maestro-tests:
  runs-on: macos-latest

  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16" # or whatever version you're using

    - name: Install dependencies
      run: |
        npm install

    - name: Install Maestro
      run: curl -fsSL "https://get.maestro.mobile.dev" | bash

    - name: Launch iOS Simulator
      id: sim
      uses: futureware-tech/simulator-action@v4
      with:
        simulator: "iPhone 16" # Adjust to your preferred simulator

    - name: Run React Native app on iOS
      run: |
        npx react-native run-ios --simulator="${{ steps.sim.outputs.udid }}"

    - name: Run Maestro acceptance tests
      run: maestro record maestro/acceptance/*.yaml --local test.mp4

    - name: Upload Test Video
      uses: actions/upload-artifact@v4
      with:
        name: test-video
        path: test.mp4
