name: CI Pipeline

on:
  push:
    branches:
      - main # Run on push to the main branch
  pull_request:
    branches:
      - main # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu image

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Run tests
        run: |
          docker-compose exec web pytest
